language: generic


services:
- docker

matrix:
  include:
  - os: linux
    env: LINUX_WHEELS=1 PYTHONWARNINGS=ignore
    install:
    - eval `python $TRAVIS_BUILD_DIR/ci/travis/determine_tests_to_run.py`
    - if [ $RAY_CI_LINUX_WHEELS_AFFECTED != "1" ]; then exit; fi
    - "./ci/suppress_output ./ci/travis/install-dependencies.sh"
    - "./ci/suppress_output docker run --rm -w /ray -v `pwd`:/ray -ti rayproject/arrow_linux_x86_64_base:latest
      /ray/python/build-wheel-manylinux1.sh"
    script:
    - if [ $RAY_CI_LINUX_WHEELS_AFFECTED != "1" ]; then exit; fi
    - "./ci/travis/test-wheels.sh"

deploy:
- provider: s3
  access_key_id: &aws_key
    secure: "xxyZ6+irrq1YEO/T2P+mBQeQtcyGpkh4Py6jchymhpEoIPcrBpzZc+E+B8JZ8pck06oe1eTC1uBhXl87iyIEIvK0TsqASUtPQ4EsNy8F7/4fe1P7J32P/wz3IM2Y/PmDaT32BCMadDVl+6TDtd+No8Mjiq4u5Bgf2R2B1vlTkMQYTZ4mnqCxNvlV34ldPakgNNkrVIwYqj1Boqu8brGr2Tr+O4dt3M7J3qXSAPQkbMh2NbjDnSjObRLMnhVj+69eD92GL6f0xP6z2jfGeDdUS39nR8UmZQ5Afmia7Tw5W+eg3ARssOjtmvAySQ8eDoQAkY03bSB/i+fP4tJXeT8qaP6x3+q46Xl8vSSyKgkXorLkGyec6JKhjiPE78ii/OMjEStWKR3OZIORpm5JaVU4DbjGYtb0t0kNlYQ3YojUDv9LdiBnQs7QgSHcBH9MCpTt4GWKqWYiPEcRDbSO0oAtJE7x/vgz57VlYnC1iBXSWxBoFKFTt/TJjPY5U1KMOu+PXFC92hw+cT/mo9DGcfJrQDEAJbZk6W85VUwt4tDBEscWjQ/UJAbF9DQsWIFDwlSq+KmyrOx/lbIO+8+e+6wCIBIgBzxGQwhhN6kqfGb9W+skjRMOGzln8AmzrJLeshmtxLo+OSqfT+GyK+VtLa1nPjahuGIbY4RxHyMd2xApynI="
  secret_access_key: &aws_secret
    secure: "wYKdz/BfEKVHDKao+WkpTnLTf0svdJKUmjpriImCeYV7qb+LHvwrv0ddNU7N7+SbGM7/nruWICvNtyvAZPjwXWEINYsvxGtI5bJJLYnOINRjnWsj7UXGje1hqZ5feBgdtxj88nrknzMWBJ4jIkNqzcaeo8GLZvKs/nZ3Lg4dOXHCUQr1MqPT/hSF51qYfVRuHatfpjnqZm5O01QGrEBrBtG24qwFcYQWb8PupI3XSgXVBpaWxb2F9FIZah+NBbw+tbVw1OC0udXrcjNaB5GGHTH8G4YXIOLhV1boLcQ6tn1IfS72Ry7YHtiRCWevONzCJye9bDWhATotfJSU9nD02MNQ4qu3i6jWwI2SHg9oXnlZlOE1812B1Z/XSCNYj+r5wpTtITNbfGuEI4p4uq1m+63YMiwsBZxmESR0X7awMf7nD/MpaBnyzMPqFkbtK0Zy0m2Zb9jt7sns0RGfiTSDkKWrPHJ5QNQmtiEohYGKND0suBU6l/v+uEUxd3EQ5r5G/QbeEObjSq4V9xA/InAfz4qBXlST/NpouBkXqFbIwMwa3AWwxmGGnn56bEYTcVLgRHNtDpVjPf/ZTfIKEBRzNRzKPHrBpkjbNPYXCAsWZyGPLYCRzTyaS+1xxZpxU6/oxq2Hlc+5/DASFWXdJRkmZF+4XbxnPK00Qm8q23y+pzc="
  bucket: public-wman
  local-dir: .whl
  upload-dir: ray/${TRAVIS_BRANCH}/${TRAVIS_COMMIT}
  acl: public_read
  skip_cleanup: true
  file_glob: true
  region: eu-west-1
  on:
    repo: wingman-ai/ray
    branch: master

- provider: s3
  access_key_id: *aws_key
  secret_access_key: *aws_secret
  bucket: public-wman
  local-dir: .whl
  upload-dir: ray/${TRAVIS_BRANCH}/latest
  acl: public_read
  skip_cleanup: true
  file_glob: true
  region: eu-west-1
  on:
    repo: wingman-ai/ray
    all_branches: true

