language: generic


services:
- docker

matrix:
  include:
  - os: linux
    env: LINUX_WHEELS=1 PYTHONWARNINGS=ignore
    install:
    - eval `python $TRAVIS_BUILD_DIR/ci/travis/determine_tests_to_run.py`
    - if [ $RAY_CI_LINUX_WHEELS_AFFECTED != "1" ]; then exit; fi
    - "./ci/suppress_output ./ci/travis/install-dependencies.sh"
    - "./ci/suppress_output docker run --rm -w /ray -v `pwd`:/ray -ti rayproject/arrow_linux_x86_64_base:latest
      /ray/python/build-wheel-manylinux1.sh"
    script:
    - if [ $RAY_CI_LINUX_WHEELS_AFFECTED != "1" ]; then exit; fi
    - "./ci/travis/test-wheels.sh"

deploy:
- provider: s3
  access_key_id: &aws_key
    secure: "Ro2/69LUjOFiAnvjQJC7MYhzPrrbm0b+e46dliXWOtIhhoM8yvoGeuFRFnyAYj5W7S8EAsV/CV9JE1SKKTVxJlOvN9jxIPCE+439JukYLv4GSCzrfHE5op8zz92sJAnouZKPERbtIZPq2nsq/9AUeg3U7CCfmDuEocpVckewa3puoCDxzoH5DRHpu1ipnLyj138G8+79beTzDGnhzAfYs00NDJ1IM9M/FKTeC5y1q52Zf0YBcSckE8r3sDpDxg9L8r4M/R7LIGcH4N1BtkMjRM2O/Y1M57eC70ZWK7dMRxctsl2W34eXSBF5D0jVvDQh3FUG+sM94WL1QhNhqz5OUnQV6uhwne5BkLgo8PeXhhvunMWqRz9wjoafq7vykM403BKq7biFFUGi8juxMIE15Kdbk8o7wm56/qZcnlwTZHRjYy3GBSa4rMW/gi49qwjgbNVYST8/qHykMo9R11Qn1p/c6v87tP/yueyalg9CsxlIi9xVPgXzXLJgdRWZu+b44zR1mxSNlRpY5TCzcbqQrz1O1jDmnxJ3PidZWoTlzLjUIl/geRa0IKlLh+nR6OSshZezc+5f4mdrCiTueNhMt2Sa2+x6/CLKDz3JB8KiEIfIljI4XKhwpXK9h0GzbmIJrE+ZjL5MKMygbyVRZQnxB+4S9t3/nvOVUqCcByrBKIQ="
  secret_access_key: &aws_secret
  	secure: "dr9PlSNqg7R/X8O5WJ5qIY6Sp6YgLKqUnWOdWH/j908azudz97Y3rcgQ/jxBRMqw2UYAd/Sl3kB3hH4Uaec51eibhWw3C/3JBI5NIIFLEHbx8irKtNewkUyLZdqP2YFiRsJw9ku01yaJEHzOG5IcwCIjQon4KwK1rkJvRi5VWA6vBxvob4Q+1moiBOwiOYiPEwaNLs9Aw6g/Efceki+MQ2vXdwYVZGXbbPcSHOxMF02i/zkuMzV5X9dQY0bthOIX+RvShcPz040XlKmBi+hzCgXt0ucy2zUrIJ/9WEp1Y03GbIllkm88EwLcCnqUoz0pq4cub9Puf+hBMLoGK0dyDbfguTIiHs0f558pk4t9laWM9cnX1n9Yrw+c6BeasD/R8ht937s13M1J9UvO/1W/y+AM6PQxSGRFGENHvLh9ze4/HS3JczvMvd1FFKb/LOnUquBBXBrijMyheEBK4rffk5HiFWUrv2F+M8RypUrskWiCAVRBpAvsihbET2mP9QLzU9lIsomdjnaqrQuKgSGsjcBerzt9gr/J2nrPBBczCRs1bE699uphQHD4Vcz9XY34tQYA/sOWcmiCxEUOBgNU9duIGHU6Sgs9v9xzcjIY+ZlDYT8KA76xfKKiVdkrjMaCZToV6nb6ho49edlYNE/BbWBvoTKE3gX1SJ9Jxg0MYdA="<Paste>
  bucket: public-wman
  local-dir: .whl
  upload-dir: ray/${TRAVIS_BRANCH}/${TRAVIS_COMMIT}
  acl: public_read
  skip_cleanup: true
  file_glob: true
  region: eu-west-1
  on:
    repo: wingman-ai/ray
    branch: master

- provider: s3
  access_key_id: *aws_key
  secret_access_key: *aws_secret
  bucket: public-wman
  local-dir: .whl
  upload-dir: ray/${TRAVIS_BRANCH}/latest
  acl: public_read
  skip_cleanup: true
  file_glob: true
  region: eu-west-1
  on:
    repo: wingman-ai/ray
    all_branches: true

